apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Simple Website</title>
    </head>
    <body>
      <h1>Pong!</h1>
    </body>
    </html>